appointments/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.entry.urls', namespace="entry")),
    url(r'^users/', include('apps.users.urls', namespace="users")),
    url(r'^appointments/', include('apps.appointments.urls', namespace="appointments")),
]

apps/appointments/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^create$', create, name="create"),
    url(r'^(?P<id>\d+)$', edit, name="edit"),
    url(r'^(?P<id>\d+)/delete$', delete, name="delete"),
]

apps/users/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', create, name="create"),
    url(r'^login$', login, name="login"),
    url(r'^logout$', logout, name="logout"),
]

apps/appointments/models.py
from __future__ import unicode_literals
from datetime import datetime
from django.utils import timezone

from django.db import models

from ..users.models import User

# Create your models here.

STATUS_TYPE_CHOICES = (
    ('0', 'Pending'),
    ('1', 'Done'),
    ('2', 'Missed'),
)

PENDING = '0'
DONE = '1'
MISSED = '2'

class AppointmentManager(models.Manager):
    def validate(self, form, u_id):
        data = {}
        errors = {}
        flag = False
        for key, val in form.iteritems():
            if key != 'csrfmiddlewaretoken':
                data[key] = str(val)

        if len(data['task']) == 0:
            errors['task'] = 'Please write a task'


        # Appointment Checks
		# Collect error prone values from kwargs and validate

        try:
            print data['time']
            task_time = datetime.strptime(data['time'], '%H:%M')

        except Exception as e:
            flag = True
            errors['time'] = "Please enter a value for time"

        try:
            print data['date']
            task_date = datetime.strptime(data['date'], '%Y-%m-%d')

        except Exception as e:
            flag = True
            errors['date'] = "Please enter a value for 'Date of Birth'"

        try:
            delta = datetime.now() - task_date
            if delta.days > 0:
                print delta
                flag = True
                errors['date'] = "I'm sorry, you may only select days today and later"
        except Exception as e:
            pass

        if flag:
            return (False, errors)
        try:
            data['user']=User.manager.get(id=u_id)
            appointment = Appointment.objects.create(**data)
        except Exception as e:
            errors['database_error'] = e
            return (False, errors)

        return (True, appointment)

class Appointment(models.Model):
    date = models.DateField()
    time = models.TimeField()
    task = models.TextField()
    status = models.CharField(max_length=1, choices=STATUS_TYPE_CHOICES, default=PENDING)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, related_name="appointment")
    objects = models.Manager()
    manager = AppointmentManager()

apps/appointments/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse

from datetime import datetime
from ..users.models import User
from .models import Appointment


# Create your views here.
def index(request):
    if 'id' not in request.session:
        return redirect(reverse('entry:index'))
    now = datetime.now()
    data ={
        'user': User.manager.get(id=request.session['id']),
        'now': now,
        'todays_apps': Appointment.objects.filter(date=now.date()),
        'future_apps': Appointment.objects.filter(date__gt=now.date()),
    }
    return render(request, 'appointments/index.html', data)

def create(request):
    result = Appointment.manager.validate(form=request.POST, u_id=request.session['id'])

    if not result[0]:
        for key, val in result[1].iteritems():
            messages.error(request, val)
    return redirect(reverse('appointments:index'))

def edit(request, id):
    if request.method == 'GET':
        data = {
            'app': Appointment.objects.get(id=id)
        }
        return render(request, 'appointments/edit.html', data)
    return redirect(reverse('appointments:index'))

def delete(request):
    return redirect(reverse('appointments:index'))

apps/appointments/templates/appointments/edit.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Welcome to Appointify!</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link href="{% static 'entry/css/main.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="container">
            <nav>
                <div class="links">
                    <a href="{% url 'appointments:index' %}">Dashboard</a>
                    <a href="{% url 'users:logout' %}">Logout</a>
                </div>
            </nav>

            <h1>Edit This Appointment!</h1>

            <div class="new-appointment">

                {{app.task}}

                <form action="{url 'appointments:create'}" method="POST">
                    {% csrf_token %}
                    <label>
                        Tasks:
                        <textarea type="text" name="task" placeholder="{{app.task}}"></textarea>
                    </label>
                    <label>
                        Status:
                        <select name="status">
                            {% if app.status == 0 %}
                            <option value="0" selected>{{app.get_status_display}}</option>
                            <option value="1">Done</option>
                            <option value="2">Neglected</option>
                            {% elif app.status == '1'%}
                            <option value="0" selected>Pending</option>
                            <option value="1">{{app.get_status_display}}</option>
                            <option value="2">Missed</option>
                            {% else %}
                            <option value="0" selected>Pending</option>
                            <option value="1">Done</option>
                            <option value="2">{{app.get_status_display}}</option>
                            {% endif %}
                        </select>
                    </label>
                    <label>
                        Date:
                        <input type="date" name="date" value="{{ app.date|date:'Y-m-d' }}">
                    </label>
                    <label>
                        Time:
                        <input type="time" name="time" value="{{app.time|time:'H:i'}}">
                    </label>

                    <button type="submit">Update</button>
                </form>
            </div>

        </div>
    </body>
</html>

apps/appointments/templates/appointments/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Welcome!</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link href="{% static 'entry/css/main.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="container">
            <nav>
                <div class="links">
                        <a href="{% url 'users:logout' %}">Logout</a>                        
                </div>
            </nav>
            <h1>Hello {{user.name}}!</h1>

            <h5>Here are your appointments for today, {{now}}</h5>

            <table>
                <thead>
                    <tr>
                        <th>Tasks</th>
                        <th>Time</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for app in todays_apps %}
                    <tr>
                        <td>{{app.task}}</td>
                        <td>{{app.time}}</td>
                        <td>{{app.get_status_display}}</td>
                        <td>
                            {% if app.status != 'Done' %}
                            <a href="{% url 'appointments:edit' id=app.id %}">Edit</a>
                            <a href="{% url 'appointments:delete' id=app.id %}">Delete</a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <h3>Future Appointments</h3>
            <table>
                <thead>
                    <tr>
                        <th>Tasks</th>
                        <th>Date</th>
                        <th>Time</th>
                    </tr>
                </thead>
                <tbody>
                    {% for app in future_apps %}
                    <tr>
                        <td>{{app.task}}</td>
                        <td>{{app.date}}</td>
                        <td>{{app.time}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <div class="new-appointment">
                
                {% if messages %}
                <ul>
                    {% for message in messages %}
                    <li {% if message.tags %}class="{{message.tags}}"{% endif %}>{{message}}</li>
                    {% endfor %}
                </ul>
                {% endif %}

                <h3>Add Appointment</h3>

                <form action="{% url 'appointments:create' %}" method="POST">
                    {% csrf_token %}                        
                    
                    <label>
                        Date:
                        <input type="date" name="date">
                    </label>
                    <label>
                        Time:
                        <input type="time" name="time">
                    </label>
                    <label>
                        Tasks:
                        <textarea name="task" cols="30" rows="10"></textarea>
                    </label>

                    <button type="submit">Add Appointment</button>
                </form>
            </div>

        </div>
    </body>
</html>