appointments/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.entry.urls', namespace="entry")),
    url(r'^users/', include('apps.users.urls', namespace="users")),
    url(r'^appointments/', include('apps.appointments.urls', namespace="appointments")),
]

apps/entry/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', redirect_index),
    url(r'^main$', index, name="index"),
]

apps/users/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', create, name="create"),
    url(r'^login$', login, name="login"),
    url(r'^logout$', logout, name="logout"),
]

apps/entry/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/entry/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse


# Create your views here.
def index(request):
    if 'id' in request.session:
        return redirect(reverse('appointments:index'))
    return render(request, 'entry/index.html')

def redirect_index(request):
    return redirect(reverse('entry:index'))

apps/entry/templates/entry/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Welcome to Appointify!</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link href="{% static 'entry/css/main.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="container">
            <h1>Welcome to Appointify!</h1>

            {% if messages %}
            <ul>
                {% for message in messages %}
                <li {% if message.tags %}class="{{message.tags}}"{% endif %}>{{message}}</li>
                {% endfor %}
            </ul>
            {% endif %}

            <div class="forms">
                <fieldset id="register-form">
                    <legend>Register</legend>

                    
                    <form action="{% url 'users:create' %}" method="POST">
                        {% csrf_token %}
                        <label>
                            Name:
                            <input type="text" name="name">
                        </label>
    
                        <label>
                            Email:
                            <input type="text" name="email">
                        </label>
    
                        <label>
                            Password:
                            <input type="text" name="password">
                        </label>
    
                        <label>
                            Confirm PW:
                            <input type="text" name="password_confirmation">
                        </label>
    
                        <label>
                            Date of Birth:
                            <input type="date" name="birthday">
                        </label>
    
                        <button type="submit">Register</button>
                    </form>
                </fieldset>
                <fieldset id="login-form">
                    <legend>Login</legend>

                    
                    <form action="{% url 'users:login' %}" method="POST">
                        {% csrf_token %}
                        <label>
                            Email:
                            <input type="text" name="email">
                        </label>
    
                        <label>
                            Password:
                            <input type="text" name="password">
                        </label>
    
                        <button type="submit">Login</button>
                    </form>
                </fieldset>
            </div>
        </div>
    </body>
</html>